### ISSUE TITLE
Register RPC method to function in another class 

### ISSUE THREAD

**Issue by Meach** [bakercp/ofxJSONRPC#11]
Hi,

I am trying to register RPC methods to functions that are in another class than ofApp.
From the example project, if I put the "getText(...)" function in a custom class of mine "customClass", I tried to register the RPC call to it in the following way:

server.registerMethod("get-text",
                          "Returns a random chunk of text to the client.",
                          this,
                          &customClass::getText);

But am only greeted with compilation error. Am I doing something wrong?

I am on windows 10, OF 0.9.8 release, VS2015

**Comment by bakercp** [comment]
Does 'this' refer to the instance of customClass?

**Comment by Meach** [comment]
Very good question. I tried many different options but didn't try to put "&myCustomClass" instead of this. Now is compiling fine. Thanks!

**Comment by bakercp** [comment]
Super.
