### ISSUE TITLE
compiling on linux64

### ISSUE THREAD

**Issue by themancalledjakob** [bakercp/ofxJSONRPC#14]
I get errors when trying to compile the example on linux:
`/home/human/git/tools/openFrameworks/addons/ofxPoco/libs/poco/lib/linux64/libPocoNetSSL.a(Context.o):Context.cpp:function Poco::Net::Context::createSSLContext(): error: undefined reference to 'SSLv23_client_method'
/home/human/git/tools/openFrameworks/addons/ofxPoco/libs/poco/lib/linux64/libPocoNetSSL.a(Context.o):Context.cpp:function Poco::Net::Context::createSSLContext(): error: undefined reference to 'SSLv23_server_method'
/home/human/git/tools/openFrameworks/addons/ofxPoco/libs/poco/lib/linux64/libPocoCrypto.a(X509Certificate.o):X509Certificate.cpp:function Poco::Crypto::X509Certificate::extractNames(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::set<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&) const: error: undefined reference to 'sk_num'
/home/human/git/tools/openFrameworks/addons/ofxPoco/libs/poco/lib/linux64/libPocoCrypto.a(X509Certificate.o):X509Certificate.cpp:function Poco::Crypto::X509Certificate::extractNames(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::set<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&) const: error: undefined reference to 'sk_value'
/home/human/git/tools/openFrameworks/addons/ofxPoco/libs/poco/lib/linux64/libPocoCrypto.a(OpenSSLInitializer.o):OpenSSLInitializer.cpp:function Poco::Crypto::OpenSSLInitializer::uninitialize(): error: undefined reference to 'EVP_cleanup'
/home/human/git/tools/openFrameworks/addons/ofxPoco/libs/poco/lib/linux64/libPocoCrypto.a(OpenSSLInitializer.o):OpenSSLInitializer.cpp:function Poco::Crypto::OpenSSLInitializer::uninitialize(): error: undefined reference to 'ERR_free_strings'
/home/human/git/tools/openFrameworks/addons/ofxPoco/libs/poco/lib/linux64/libPocoCrypto.a(OpenSSLInitializer.o):OpenSSLInitializer.cpp:function Poco::Crypto::OpenSSLInitializer::uninitialize(): error: undefined reference to 'CRYPTO_set_locking_callback'
/home/human/git/tools/openFrameworks/addons/ofxPoco/libs/poco/lib/linux64/libPocoCrypto.a(OpenSSLInitializer.o):OpenSSLInitializer.cpp:function Poco::Crypto::OpenSSLInitializer::uninitialize(): error: undefined reference to 'CRYPTO_set_id_callback'
/home/human/git/tools/openFrameworks/addons/ofxPoco/libs/poco/lib/linux64/libPocoCrypto.a(OpenSSLInitializer.o):OpenSSLInitializer.cpp:function Poco::Crypto::OpenSSLInitializer::initialize(): error: undefined reference to 'SSL_library_init'
/home/human/git/tools/openFrameworks/addons/ofxPoco/libs/poco/lib/linux64/libPocoCrypto.a(OpenSSLInitializer.o):OpenSSLInitializer.cpp:function Poco::Crypto::OpenSSLInitializer::initialize(): error: undefined reference to 'SSL_load_error_strings'
/home/human/git/tools/openFrameworks/addons/ofxPoco/libs/poco/lib/linux64/libPocoCrypto.a(OpenSSLInitializer.o):OpenSSLInitializer.cpp:function Poco::Crypto::OpenSSLInitializer::initialize(): error: undefined reference to 'OPENSSL_add_all_algorithms_noconf'
/home/human/git/tools/openFrameworks/addons/ofxPoco/libs/poco/lib/linux64/libPocoCrypto.a(OpenSSLInitializer.o):OpenSSLInitializer.cpp:function Poco::Crypto::OpenSSLInitializer::initialize(): error: undefined reference to 'CRYPTO_num_locks'
/home/human/git/tools/openFrameworks/addons/ofxPoco/libs/poco/lib/linux64/libPocoCrypto.a(OpenSSLInitializer.o):OpenSSLInitializer.cpp:function Poco::Crypto::OpenSSLInitializer::initialize(): error: undefined reference to 'CRYPTO_set_locking_callback'
/home/human/git/tools/openFrameworks/addons/ofxPoco/libs/poco/lib/linux64/libPocoCrypto.a(OpenSSLInitializer.o):OpenSSLInitializer.cpp:function Poco::Crypto::OpenSSLInitializer::initialize(): error: undefined reference to 'CRYPTO_set_id_callback'
/home/human/git/tools/openFrameworks/addons/ofxPoco/libs/poco/lib/linux64/libPocoCrypto.a(OpenSSLInitializer.o):OpenSSLInitializer.cpp:function Poco::Crypto::OpenSSLInitializer::initialize(): error: undefined reference to 'CRYPTO_set_dynlock_create_callback'
/home/human/git/tools/openFrameworks/addons/ofxPoco/libs/poco/lib/linux64/libPocoCrypto.a(OpenSSLInitializer.o):OpenSSLInitializer.cpp:function Poco::Crypto::OpenSSLInitializer::initialize(): error: undefined reference to 'CRYPTO_set_dynlock_lock_callback'
/home/human/git/tools/openFrameworks/addons/ofxPoco/libs/poco/lib/linux64/libPocoCrypto.a(OpenSSLInitializer.o):OpenSSLInitializer.cpp:function Poco::Crypto::OpenSSLInitializer::initialize(): error: undefined reference to 'CRYPTO_set_dynlock_destroy_callback'
/home/human/git/tools/openFrameworks/addons/ofxPoco/libs/poco/lib/linux64/libPocoCrypto.a(OpenSSLInitializer.o):OpenSSLInitializer.cpp:function Poco::Crypto::OpenSSLInitializer::uninitialize(): error: undefined reference to 'CONF_modules_free'
collect2: error: ld returned 1 exit status
make[1]: *** [/home/human/git/tools/openFrameworks/libs/openFrameworksCompiled/project/makefileCommon/compile.project.mk:405: bin/example] Error 1
make[1]: Leaving directory '/home/human/git/tools/openFrameworks/addons/ofxJSONRPC/example'
make: *** [/home/human/git/tools/openFrameworks/libs/openFrameworksCompiled/project/makefileCommon/compile.project.mk:129: Release] Error 2`

I use master branch of openframeworks and cloned the master branches of the dependencies...
what am I missing? Is there something wrong with poco?

**Comment by bakercp** [comment]
Usually if there is a problem with Poco or other linker problems on Linux it's because of a mismatch between compiler / platform / precompiled libraries, etc.  What version of gcc and linux are you using?

**Comment by themancalledjakob** [comment]
right! thanks a lot for replying.
I use Manjaro Linux, an Archlinux based distribution.

I'll give you here the output of my commands:
uname -a:
`Linux transporter 4.14.78-1-MANJARO #1 SMP PREEMPT Sun Oct 21 07:57:51 UTC 2018 x86_64 GNU/Linux`
gcc --version:
`gcc (GCC) 8.2.1 20180831`

All examples or libraries I tried so far which don't rely on Poco are working without issues.

**Comment by bakercp** [comment]
I'm not sure - though I suspect it's an archlinux thing.  Since this isn't an ofxJSONRPC specific problem (it tested and works on Ubuntu / Mint based distros) I'm going to recommend checking on the oF forum.  

Here is an example with similar errors and a solution:

https://forum.openframeworks.cc/t/archlinux-problem-with-openssl-undefined-references/26605

Basically, you need to recompile Poco for your system and the easiest way to do that is to use our apothecary build system.

I'm going to close this issue for now, but if you are still having problems that seem to be directly related to the addon, please feel free to reopen.  Good luck!

CB

**Comment by themancalledjakob** [comment]
okay, thanks a lot for the link. Unfortunately the solution doesn't work for me.
I'm gonna port everything to Ubuntu and hope it works then.

[Edit] installed a fresh Ubuntu 18.04, same problem here.
I'm not going to reopen the issue, since it seems indeed a problem not directly related to the addon, but to a general incompatibility with the installed poco version and openssl 1.1.0...
If I'll find the proper fix, I'm gonna post it here anyway in case somebody stumbles over it here
