### ISSUE TITLE
Front-end error callback never reached

### ISSUE THREAD

**Issue by brannondorsey** [bakercp/ofxJSONRPC#3]
It appears that setting `args.error["foo"] = "bar"` in an ofxJSONRPC server method may not throw the error callback when using [jquery.jsonrpcclient.js](https://github.com/Textalk/jquery.jsonrpcclient.js).

**Comment by bakercp** [comment]
By the way, I think I fixed this ... can you give it a try with the latest develop?

**Comment by bakercp** [comment]
@brannondorsey do you know if this was fixed?

**Comment by brannondorsey** [comment]
Hm... I don't remember the project that I was using this for but I can test the functionality that I described in the initial issue comment and get back to you!

**Comment by bakercp** [comment]
Closing this for now. @brannondorsey plz reopen if you discover it again.
