### ISSUE TITLE
send long strings from client to server

### ISSUE THREAD

**Issue by doktorsuarez** [bakercp/ofxJSONRPC#5]
Hi there,
I get an error when i send long strings from client to server, the other way round it works fine! 
According to this
http://stackoverflow.com/questions/14102862/websocket-is-not-able-to-send-large-data
 I need to change the payload length of the websocket frame. 
Would be happy about a hint, where to do that. Or is fragmenting the string manually on client-side the way to go?

Greets Oli

**Comment by bakercp** [comment]
You should be able to change the websocket buffer by using the `setBufferSize` method of the `BasicJSONRPCServerSettings`.

**Comment by doktorsuarez** [comment]
that did it! super, thanks!

**Comment by bakercp** [comment]
What value did you end up using?  I might make the default bigger again (I ran into this problem on another project).

**Comment by doktorsuarez** [comment]
sorry for delay:
i*m using this at the moment: 
 settings.setBufferSize(2000000);

i fear its quite high, but works fine!
