### ISSUE TITLE
Compilation error on Ubuntu: no member named ‘getConnectionRef’

### ISSUE THREAD

**Issue by Meach** [bakercp/ofxJSONRPC#6]
Hello,

I am trying to compile your addon on a fresh Ubuntu installation.
I generated a new project, using the PG and when compiling, I get those errors:

> ../../../addons/ofxJSONRPC/libs/ofxHTTP/src/BasicJSONRPCServer.cpp|94|error: ‘class ofx::HTTP::WebSocketFrameEventArgs’ has no member named ‘getConnectionRef’|
> ../../../addons/ofxJSONRPC/libs/ofxHTTP/src/BasicJSONRPCServer.cpp|99|error: ‘class ofx::HTTP::WebSocketFrameEventArgs’ has no member named ‘getConnectionRef’|
> ../../../addons/ofxJSONRPC/libs/ofxHTTP/src/BasicJSONRPCServer.cpp|107|error: ‘class ofx::HTTP::WebSocketFrameEventArgs’ has no member named ‘getConnectionRef’|

Any ideas where are those coming from?
Thanks

**Comment by bakercp** [comment]
I'm in the middle of updating a few things -- this should be working if you use the develop branches of ofxHTTP and ofxJSONRPC.  Can you give them a try?

**Comment by Meach** [comment]
I just tried it and got different errors:

> ../../../addons/ofxHTTP/libs/ofxHTTP/src/WebSocketConnection.cpp|147|error: ‘class ofx::HTTP::WebSocketFrame’ has no member named ‘getData’|
> ../../../addons/ofxHTTP/libs/ofxHTTP/src/WebSocketConnection.cpp|215|error: ‘class ofx::HTTP::WebSocketFrame’ has no member named ‘getData’|

**Comment by bakercp** [comment]
Ahh to use develop the master brach of of is required. Let me see if I can
get this sorted out ...

**Comment by Meach** [comment]
ah ok, yes I forgot to mention that I am using the linux version of OF, downloaded from the website.

**Comment by bakercp** [comment]
OK.  You should be able to use the develop branch of JSONRPC w/ the develop branch of ofxHTTP and the stable branch of openFrameworks (the one you downloaded from the web!).

Can you give it try?  Thanks!

**Comment by Meach** [comment]
Ok now the empty project compiles fine.

Then I tried with another project, realised that it needs to have ofxNetwork included too....made few changes to use your new changes and it compiled fine.

Thanks!

**Comment by bakercp** [comment]
Closing this as it seems to work now.  Thanks!
